// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Projeto_Integrador.Models;

public partial class Cliente
{
    public int CliCodigo { get; set; }

    public string CliNome { get; set; }

    public string CliSexo { get; set; }

    public string CliCpfcnpj { get; set; }

    public string CliTelefone { get; set; }

    public string CliEmail { get; set; }

    public DateTime? CliDataNascimento { get; set; }

    public string CliNomeMae { get; set; }

    public DateTime? CliDataCadastro { get; set; }

    public virtual ICollection<Endereco> Endereco { get; set; } = new List<Endereco>();

    public virtual ICollection<Venda> Venda { get; set; } = new List<Venda>();
}