// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Projeto_Integrador.Models;

public partial class ItensVenda
{
    public int ItvCodigoVenda { get; set; }

    public int ItvCodigoProduto { get; set; }

    public string ItvValorItem { get; set; }

    public virtual Produto ItvCodigoProdutoNavigation { get; set; }

    public virtual Venda ItvCodigoVendaNavigation { get; set; }
}