// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Projeto_Integrador.Models;

public partial class TipoPagamento
{
    public int TpgCodigo { get; set; }

    public string TpgDescricao { get; set; }

    public bool TpgDesativado { get; set; }

    public virtual ICollection<Venda> Venda { get; set; } = new List<Venda>();
}