// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Projeto_Integrador.Models.Models;

public partial class CadDoacao
{
    public int Id { get; set; }

    public string IdFichaUsuario { get; set; }

    public int IdData { get; set; }

    public int IdStatus { get; set; }

    public int IdLocal { get; set; }
}