// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Projeto_Integrador.Models.Models;

public partial class DOACAO_SANGUEContext : DbContext
{
    public DOACAO_SANGUEContext(DbContextOptions<DOACAO_SANGUEContext> options)
        : base(options)
    {
    }

    public DOACAO_SANGUEContext()
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)

=> optionsBuilder.UseSqlServer("data source=DANIEL\\SQLEXPRESS;Initial Catalog=DOACAO_SANGUE;User Id=sa;Password=D@nielPeralba;TrustserverCertificate=True");

    public virtual DbSet<CadDataHoraDisp> CadDataHoraDisp { get; set; }

    public virtual DbSet<CadDoacao> CadDoacao { get; set; }

    public virtual DbSet<CadEndereco> CadEndereco { get; set; }

    public virtual DbSet<CadLocalDoacao> CadLocalDoacao { get; set; }

    public virtual DbSet<FichaDoacao> FichaDoacao { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CadDataHoraDisp>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CAD_DATA__3214EC270A3F9E18");

            entity.ToTable("CAD_DATA_HORA_DISP");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.DataDisp)
                .HasColumnType("datetime")
                .HasColumnName("DATA_DISP");
            entity.Property(e => e.Disp).HasColumnName("DISP");
            entity.Property(e => e.IdLocal).HasColumnName("ID_LOCAL");

            entity.HasOne(d => d.IdLocalNavigation).WithMany(p => p.CadDataHoraDisp)
                .HasForeignKey(d => d.IdLocal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CAD_DATA_HORA_DISP_fk0");
        });

        modelBuilder.Entity<CadDoacao>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CAD_DOAC__3214EC27087CD3B9");

            entity.ToTable("CAD_DOACAO");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.DataHora)
                .HasColumnType("datetime")
                .HasColumnName("DATA_HORA");
            entity.Property(e => e.IdFichaUsuario).HasColumnName("ID_FICHA_USUARIO");
            entity.Property(e => e.IdLocal).HasColumnName("ID_LOCAL");
            entity.Property(e => e.Status).HasColumnName("STATUS");

            entity.HasOne(d => d.IdFichaUsuarioNavigation).WithMany(p => p.CadDoacao)
                .HasForeignKey(d => d.IdFichaUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CAD_DOACAO_fk0");

            entity.HasOne(d => d.IdLocalNavigation).WithMany(p => p.CadDoacao)
                .HasForeignKey(d => d.IdLocal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CAD_DOACAO_fk1");
        });

        modelBuilder.Entity<CadEndereco>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CAD_ENDE__3214EC2786B0E586");

            entity.ToTable("CAD_ENDERECO");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Bairro)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("BAIRRO");
            entity.Property(e => e.Cep)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("CEP");
            entity.Property(e => e.Cidade)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CIDADE");
            entity.Property(e => e.Complemento)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("COMPLEMENTO");
            entity.Property(e => e.Estado)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ESTADO");
            entity.Property(e => e.IdUser)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("ID_User");
            entity.Property(e => e.Logradouro)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("LOGRADOURO");
            entity.Property(e => e.Numero)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("NUMERO");
        });

        modelBuilder.Entity<CadLocalDoacao>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CAD_LOCA__3214EC27E27A522C");

            entity.ToTable("CAD_LOCAL_DOACAO");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Ativo).HasColumnName("ATIVO");
            entity.Property(e => e.Bairro)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("BAIRRO");
            entity.Property(e => e.Cep)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("CEP");
            entity.Property(e => e.Cidade)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CIDADE");
            entity.Property(e => e.Complemento)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("COMPLEMENTO");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("EMAIL");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ESTADO");
            entity.Property(e => e.Logradouro)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("LOGRADOURO");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NOME");
            entity.Property(e => e.Numero)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NUMERO");
            entity.Property(e => e.Telefone)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("TELEFONE");
        });

        modelBuilder.Entity<FichaDoacao>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FICHA_DO__3214EC277B4D4718");

            entity.ToTable("FICHA_DOACAO");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Cpf)
                .IsRequired()
                .HasMaxLength(17)
                .IsUnicode(false)
                .HasColumnName("CPF");
            entity.Property(e => e.DataNasc)
                .HasColumnType("datetime")
                .HasColumnName("DATA_NASC");
            entity.Property(e => e.Fumante).HasColumnName("FUMANTE");
            entity.Property(e => e.IdUser)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("ID_User");
            entity.Property(e => e.NomeMae)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NOME_MAE");
            entity.Property(e => e.NomePai)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NOME_PAI");
            entity.Property(e => e.OrgExp)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("ORG_EXP");
            entity.Property(e => e.Peso).HasColumnName("PESO");
            entity.Property(e => e.Profissao)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("PROFISSAO");
            entity.Property(e => e.Religiao)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("RELIGIAO");
            entity.Property(e => e.Rg)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("RG");
            entity.Property(e => e.Sexo)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("SEXO");
            entity.Property(e => e.TempFumante)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("TEMP_FUMANTE");
            entity.Property(e => e.TipoSangue)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("TIPO_SANGUE");
            entity.Property(e => e.UltimaDoacao)
                .HasColumnType("datetime")
                .HasColumnName("ULTIMA_DOACAO");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}