// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Projeto_Integrador.Models.Models;

public partial class FichaDoacao
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public string TipoSangue { get; set; }

    public DateTime UltimaDoacao { get; set; }

    public int Peso { get; set; }

    public int Fumante { get; set; }

    public string TempFumante { get; set; }

    public virtual ICollection<CadDoacao> CadDoacao { get; set; } = new List<CadDoacao>();

    public virtual CadDoador IdUsuarioNavigation { get; set; }
}