// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Projeto_Integrador.Models.Models;

public partial class FichaDoacao
{
    public int Id { get; set; }

    public string IdUser { get; set; }

    public string TipoSangue { get; set; }

    public DateTime UltimaDoacao { get; set; }

    public int Peso { get; set; }

    public int Fumante { get; set; }

    public string Sexo { get; set; }

    public string Cpf { get; set; }

    public string Rg { get; set; }

    public string OrgExp { get; set; }

    public string Profissao { get; set; }

    public string Religiao { get; set; }

    public string TempFumante { get; set; }

    public DateTime? DataNasc { get; set; }

    public string NomeMae { get; set; }

    public string NomePai { get; set; }

    public virtual ICollection<CadDoacao> CadDoacao { get; set; } = new List<CadDoacao>();
}