// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Projeto_Integrador.Models.Models;

public partial class StatusDoacao
{
    public int Id { get; set; }

    public string Descricao { get; set; }
}